version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: lease_postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lease_net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: lease_pgadmin
    restart: unless-stopped
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - lease_net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lease_app
    depends_on:
      - postgres
    env_file: .env
    environment:
      DB_HOST: postgres
    ports:
      - "8080:8080"
    networks:
      - lease_net
    restart: unless-stopped

volumes:
  pgdata:

networks:
  lease_net:
    driver: bridge