version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: car_rental_postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - car_rental_net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: car_rental_pgadmin
    restart: unless-stopped
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - car_rental_net

volumes:
  postgres_data:

networks:
  car_rental_net:
    driver: bridge
