spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:car_rental}
    username: ${DB_USER:car_rental}
    password: ${DB_PASSWORD:car_rental}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8087